### ISSUE TITLE
additions to template

### ISSUE THREAD

**Issue by 392781** [UCSB-PSTAT/comm160ds-container-image#8]
add docker-compose changes to https://github.com/UCSB-PSTAT/devcontainer-template

**Comment by ParadoxGuitarist** [comment]
Hey @392781 I think you might have opened this issue on the wrong repo. :) 

If not, can we at least add what packages/changes are needed for the comm160ds image?

**Comment by 392781** [comment]
Project interface bugged out on me earlier this week... I wouldn't be surprised if I opened more issues in unrelated repos :^(
